import { FormEvent, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import type { BridgeInput, CrossChainLink, LabelInput, SyncJob, TraceJob, Transfer } from "../api/types";
import { chainLabel, formatChainAmount, shortAddress } from "../lib/format";
import { WriteForms } from "./WriteForms";

type Tab = "facts" | "transactions" | "jobs" | "bridges" | "write";
interface Props { facts: Transfer[]; hasMore?: boolean; loadingMore?: boolean; onMore: () => void; traceJob?: TraceJob; syncJobs: SyncJob[]; bridges: CrossChainLink[]; chain: "ethereum"|"base"; address: string; onLabel: (input: LabelInput) => Promise<void>; onBridge: (input: BridgeInput) => Promise<void>; onAnalyzeBridge?:(txHash:string)=>Promise<void>; onSyncBridge?:(id:string)=>Promise<void> }
export function BottomPanel({ facts, hasMore, loadingMore, onMore, traceJob, syncJobs, bridges, chain, address, onLabel, onBridge, onAnalyzeBridge=async()=>{}, onSyncBridge=async()=>{} }: Props) {
 const [tab,setTab]=useState<Tab>("facts");
 return <section className="bottom-panel"><nav>{([['facts','事实边'],['transactions','交易明细'],['jobs','任务进度'],['bridges','桥接关系'],['write','写入证据']] as [Tab,string][]).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}{id==='facts'&&<span>{facts.length}</span>}</button>)}</nav><div className="tab-body">
 {tab==='facts'&&<FactTable facts={facts} hasMore={hasMore} loadingMore={loadingMore} onMore={onMore}/>} {tab==='transactions'&&<FactTable facts={facts} detailed hasMore={hasMore} loadingMore={loadingMore} onMore={onMore}/>}
 {tab==='jobs'&&<div className="job-list">{traceJob&&<div className="job-card trace-job"><div className="job-heading"><div><span className="job-kind">追踪任务</span><code>{shortAddress(traceJob.id,6)}</code></div><Status value={traceJob.status}/></div><progress max={traceJob.depth||1} value={traceJob.currentDepth}/><div className="job-metrics"><Metric label="当前深度" value={`${traceJob.currentDepth} / ${traceJob.depth}`}/><Metric label="已访问节点" value={traceJob.visitedNodes}/><Metric label="事实边" value={traceJob.edgeCount}/></div></div>}{syncJobs.map(j=><SyncProgressCard job={j} key={j.jobId}/>)}{!traceJob&&!syncJobs.length&&<Empty text="当前没有任务"/>}</div>}
 {tab==='bridges'&&<BridgeList bridges={bridges} chain={chain} onAnalyze={onAnalyzeBridge} onSync={onSyncBridge}/>}
 {tab==='write'&&<WriteForms chain={chain} address={address} onLabel={onLabel} onBridge={onBridge}/>} </div></section>;
}
function BridgeList({bridges,chain,onAnalyze,onSync}:{bridges:CrossChainLink[];chain:"ethereum"|"base";onAnalyze:(hash:string)=>Promise<void>;onSync:(id:string)=>Promise<void>}) { const [hash,setHash]=useState(""); const [message,setMessage]=useState(""); const submit=async(e:FormEvent)=>{e.preventDefault();try{await onAnalyze(hash);setMessage("识别完成")}catch(error){setMessage(error instanceof Error?error.message:"识别失败")}}; return <div className="bridge-list"><form className="bridge-analyze" onSubmit={submit}><select aria-label="桥交易网络" defaultValue={chain} name="chain" disabled><option value="ethereum">Ethereum</option><option value="base">Base</option></select><input aria-label="跨链交易哈希" placeholder="跨链源交易哈希" value={hash} onChange={e=>setHash(e.target.value)}/><button title="识别跨链交易"><Search size={14}/></button>{message&&<span>{message}</span>}</form>{bridges.length?bridges.map(b=>{const pending=['initiated','proven','finalized'].includes(b.status??'');return <div className={`bridge-row ${b.status??''}`} key={b.identityKey??`${b.sourceTxHash}-${b.targetTxHash}`}><strong>{chainLabel(b.sourceChain)} → {chainLabel(b.targetChain)}<small>{b.direction==='withdrawal'?'提款':'存款'} · {b.protocol??'人工证据'}</small></strong><span>{b.sourceAsset} {b.sourceAmount}</span><code>{shortAddress(b.targetTxHash??'待确认',8)}</code><span>{bridgeStatus(b.status)}</span>{pending&&b.id&&<button title="刷新桥接状态" onClick={()=>onSync(b.id!)}><RefreshCw size={14}/></button>}</div>}):<Empty text="当前地址没有桥接关系"/>}</div> }
function bridgeStatus(status?:string){return ({initiated:'已发起',proven:'已证明',finalized:'待执行',completed:'已到账',confirmed:'人工确认',ambiguous:'证据冲突',failed:'失败'} as Record<string,string>)[status??'']??status}
function SyncProgressCard({job}:{job:SyncJob}) { const progress=job.progress; const processed=job.processedAddresses??job.completedAddresses; return <div className="job-card"><div className="job-heading"><div><span className="job-kind">数据同步</span><code>{shortAddress(progress?.currentAddress||job.address,8)}</code></div><Status value={job.status}/></div><div className="job-address-progress"><span>地址进度 {processed} / {job.totalAddresses} · 成功 {job.completedAddresses}</span><strong>{Math.round(processed/Math.max(job.totalAddresses,1)*100)}%</strong></div><progress max={job.totalAddresses||1} value={processed}/>{progress&&<><div className="job-current"><span>{actionLabel(progress.currentAction)}</span><code>第 {progress.currentPage||0} 页</code><span>区块 {formatNumber(progress.rangeStart)} - {formatNumber(progress.rangeEnd)}</span></div><div className="job-metrics"><Metric label="累计 API 页" value={progress.pagesFetched}/><Metric label="API 已读取" value={`${formatNumber(progress.recordsRead)} 条`}/><Metric label="Mongo 已写入" value={`${formatNumber(progress.recordsWritten)} 条`}/><Metric label="区间拆分" value={`${progress.splitCount} 次`}/></div></>}{!progress&&<div className="job-metrics"><Metric label="已获取" value={`${formatNumber(job.fetched)} 条`}/></div>}{job.error&&<p className="job-error">{job.error}</p>}</div> }
function Metric({label,value}:{label:string;value:string|number}) { return <div><span>{label}</span><strong>{typeof value==='number'?formatNumber(value):value}</strong></div> }
function Status({value}:{value:string}) { const labels:Record<string,string>={queued:'排队中',waiting_sync:'等待同步',running:'运行中',succeeded:'已完成',partial:'部分完成',failed:'失败'}; return <span className={`job-status ${value}`}>{labels[value]??value}</span> }
function actionLabel(action?:string) { return ({txlist:'普通 ETH',txlistinternal:'内部 ETH',tokentx:'ERC-20'} as Record<string,string>)[action??'']??'准备请求' }
function formatNumber(value?:number) { return (value??0).toLocaleString('zh-CN') }
function FactTable({facts,detailed=false,hasMore,loadingMore,onMore}:{facts:Transfer[];detailed?:boolean;hasMore?:boolean;loadingMore?:boolean;onMore:()=>void}) { if(!facts.length)return <Empty text="当前查询没有事实边"/>; return <div className="fact-table"><div className="table-head"><span>区块 / 时间</span><span>方向</span><span>资产</span><span>原始金额</span><span>交易</span></div>{facts.map((f,i)=><div className="table-row" key={`${f.txHash}-${f.logIndex}-${i}`}><span>#{f.blockNumber}{detailed&&f.blockTime?<small>{new Date(f.blockTime).toLocaleString('zh-CN')}</small>:null}</span><span><code>{shortAddress(f.from)}</code> → <code>{shortAddress(f.to)}</code></span><span>{f.symbol||f.asset}<small>{f.source}{f.transferKind&&` · ${f.transferKind}`}</small></span><span>{formatChainAmount(f.amount||f.tokenValue,f.tokenMetadataComplete===false?undefined:f.decimals)}</span><code>{shortAddress(f.txHash,8)}</code></div>)}{hasMore&&<button className="load-more" disabled={loadingMore} onClick={onMore}>{loadingMore?'加载中':'加载更多事实边'}</button>}</div> }
function Empty({text}:{text:string}){return <div className="tab-empty">{text}</div>}
